# Main configuration for Logwatch LLM CLI

# LLM model to use for analysis (e.g., gpt-4o, claude-3-5-haiku-latest)
model = "gpt-4o"

# Enable verbose logging
verbose = true

# Email address for sending reports
email = "reichl@meap.cz"
